name: tests

on:
  push:
    branches:
      - test
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          coverage: xdebug
          extensions: pdo, pdo_sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Passport keys
        run: php artisan passport:keys --force

      - name: Configure Database
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Run Tests
        shell: bash
        run: |
          if [ -x ./vendor/bin/pest ]; then
            ./vendor/bin/pest --colors=always
          elif [ -x ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit --colors=always
          else
            echo "No test runner found (pest/phpunit) - skipping tests"
          fi
